const dares = {
    romantic: [
        "Give your partner a long, deep hug.",
        "Kiss your partner’s forehead softly.",
        "Write a sweet love note and hide it for your partner to find later.",
        "Slow dance together to a romantic song.",
        "Give your partner a romantic compliment in the sexiest way possible.",
        "Stare into your partner’s eyes for 30 seconds without looking away.",
        "Cook your partner’s favorite meal and serve it to them.",
        "Draw a warm bath for your partner and add rose petals.",
        "Whisper 'I love you' in their ear three times.",
        "Plan a surprise date night for your partner.",
        "Write a poem about your partner and read it to them.",
        "Hold hands with your partner for the next 10 minutes.",
        "Give your partner a gentle back massage.",
        "Tell your partner three things you admire about them.",
        "Recreate your first date together.",
        "Surprise your partner with breakfast in bed.",
        "Write 'I love you' on a mirror with lipstick.",
        "Take a walk together under the stars.",
        "Leave a trail of sticky notes with sweet messages for your partner to find.",
        "Watch the sunset together and cuddle.",
        "Send your partner a flirty text message.",
        "Kiss your partner’s hand like a prince/princess.",
        "Tell your partner a story about how you fell in love with them.",
        "Give your partner a piggyback ride around the room.",
        "Write a list of 10 reasons why you love your partner.",
        "Play a romantic song and sing along to it for your partner.",
        "Surprise your partner with a small gift they’ve been wanting.",
        "Kiss your partner’s cheek and whisper something sweet.",
        "Take a selfie together and make it your phone wallpaper.",
        "Write a love letter and mail it to your partner.",
        "Plan a weekend getaway for just the two of you.",
        "Tell your partner your favorite memory of them.",
        "Give your partner a foot massage.",
        "Surprise your partner with a candlelit dinner.",
        "Kiss your partner’s neck gently.",
        "Write your partner’s name in the sand or snow and send them a picture.",
        "Tell your partner what you love most about their smile.",
        "Recreate your first kiss.",
        "Give your partner a surprise kiss when they least expect it.",
        "Tell your partner how much they mean to you in 10 words or less.",
        "Surprise your partner with a bouquet of their favorite flowers.",
        "Write a song about your partner and sing it to them.",
        "Tell your partner what you dream about for your future together.",
        "Give your partner a warm blanket and cuddle them tightly.",
        "Kiss your partner’s shoulder softly.",
        "Tell your partner how they make your life better.",
        "Surprise your partner with a love playlist.",
        "Write a message in the steam on the bathroom mirror for your partner to find.",
        "Tell your partner how much you appreciate them.",
        "Kiss your partner’s nose and call them cute.",
    ],
    fun: [
        "Do an impression of your partner for 30 seconds.",
        "Sing a love song in a funny accent.",
        "Do your best impression of a chicken for 20 seconds.",
        "Act like a monkey for 30 seconds.",
        "Pretend to be a cat for the next 5 minutes.",
        "Do a silly dance for 1 minute.",
        "Speak in rhymes for the next 3 minutes.",
        "Wear socks on your hands for the next 10 minutes.",
        "Try to lick your elbow.",
        "Do 10 push-ups while singing 'Twinkle Twinkle Little Star.'",
        "Try to juggle three random objects.",
        "Do a handstand against the wall for 10 seconds.",
        "Pretend to be a news anchor reporting on your day.",
        "Try to touch your nose with your tongue.",
        "Do the worm dance move.",
        "Sing the alphabet backward.",
        "Do 20 jumping jacks while making monkey noises.",
        "Pretend to be a robot for the next 5 minutes.",
        "Try to balance a spoon on your nose for 30 seconds.",
        "Do a cartwheel (or attempt one).",
        "Speak in a British accent for the next 5 minutes.",
        "Try to do the splits.",
        "Do a dramatic reading of a children’s book.",
        "Pretend to be a dinosaur for the next 3 minutes.",
        "Try to hula hoop for 1 minute.",
        "Do a rap about your day.",
        "Pretend to be a celebrity and give an autograph.",
        "Try to spin around 10 times and then walk in a straight line.",
        "Do a magic trick (real or fake).",
        "Pretend to be a statue and let your partner pose you.",
        "Try to do a backflip (safely!).",
        "Do a TikTok dance.",
        "Pretend to be a superhero and create your origin story.",
        "Try to whistle with your fingers.",
        "Do a dramatic reenactment of your favorite movie scene.",
        "Pretend to be a pirate and talk like one for 5 minutes.",
        "Try to do a headstand.",
        "Do a silly walk for 1 minute.",
        "Pretend to be a chef and describe a dish you’re 'cooking.'",
        "Try to balance a book on your head while walking.",
        "Do a funny face and hold it for 30 seconds.",
        "Pretend to be a lion and roar as loudly as you can.",
        "Try to do a somersault.",
        "Do a dramatic interpretation of a famous painting.",
        "Pretend to be a ghost and float around the room.",
        "Try to do a handshake with your partner using only your elbows.",
        "Do a silly voice for the next 5 minutes.",
        "Pretend to be a mermaid and 'swim' around the room.",
        "Try to do a backbend.",
    ],
    spicy: [
        "Give your partner a 10-second deep kiss.",
        "Whisper the naughtiest thing you can think of in their ear.",
        "Gently run your fingers through your partner’s hair.",
        "Kiss along your partner’s jawline slowly.",
        "Lightly bite your partner's lower lip.",
        "Give your partner a sensual neck massage.",
        "Whisper what you want to do to your partner later.",
        "Kiss your partner’s collarbone gently.",
        "Playfully nibble on your partner’s ear.",
        "Trace your finger along your partner’s arm slowly.",
        "Give your partner a lingering kiss on the wrist.",
        "Whisper a fantasy you have about your partner.",
        "Kiss your partner’s shoulder and work your way up to their neck.",
        "Gently blow on your partner’s neck.",
        "Run your hands along your partner’s back slowly.",
        "Kiss your partner’s hand and work your way up their arm.",
        "Whisper how much you want your partner right now.",
        "Playfully bite your partner’s earlobe.",
        "Kiss your partner’s neck and leave a small mark.",
        "Run your fingers along your partner’s thigh.",
        "Whisper what you love most about your partner’s body.",
        "Kiss your partner’s chest gently.",
        "Playfully pull your partner closer by their waist.",
        "Whisper how irresistible your partner is.",
        "Kiss your partner’s back slowly.",
        "Run your hands through your partner’s hair and pull gently.",
        "Whisper what you’d do if you were alone with your partner right now.",
        "Kiss your partner’s stomach softly.",
        "Playfully bite your partner’s lower lip.",
        "Whisper how much your partner turns you on.",
        "Kiss your partner’s ear and whisper something naughty.",
        "Run your hands along your partner’s sides slowly.",
        "Whisper how much you love your partner’s scent.",
        "Kiss your partner’s neck and whisper how much you want them.",
        "Playfully nibble on your partner’s shoulder.",
        "Whisper how much you love your partner’s touch.",
        "Kiss your partner’s lips and leave them wanting more.",
        "Run your hands along your partner’s legs slowly.",
        "Whisper how much you love your partner’s voice.",
        "Kiss your partner’s cheek and whisper something seductive.",
        "Playfully bite your partner’s neck.",
        "Whisper how much you love your partner’s lips.",
        "Kiss your partner’s collarbone and work your way up to their neck.",
        "Run your hands along your partner’s arms slowly.",
        "Whisper how much you love your partner’s eyes.",
        "Kiss your partner’s neck and whisper how much you love them.",
        "Playfully nibble on your partner’s ear and whisper something naughty.",
        "Run your hands along your partner’s back and pull them closer.",
        "Whisper how much you love your partner’s body.",
        "Kiss your partner’s lips and leave them breathless.",
    ],
    home_alone: [
        "Send your partner a flirty text describing what you want to do to them later.",
        "Whisper in your partner’s ear exactly how you’re going to pleasure them tonight.",
        "Slowly unbutton your partner’s shirt while maintaining eye contact.",
        "Playfully blindfold your partner and tease them with light touches.",
        "Give your partner a sensual massage, focusing on their most sensitive areas.",
        "Kiss your partner passionately, then pull away just as they lean in for more.",
        "Run an ice cube along your partner’s body and watch their reaction.",
        "Whisper a fantasy you’ve never shared with your partner before.",
        "Playfully handcuff your partner (with consent) and tease them mercilessly.",
        "Strip slowly for your partner while maintaining intense eye contact.",
        "Write a naughty note and leave it somewhere your partner will find it unexpectedly.",
        "Kiss your partner’s inner thigh and work your way up slowly.",
        "Playfully nibble on your partner’s ear while whispering something seductive.",
        "Run your fingers along your partner’s waistband and tease them by stopping just short.",
        "Give your partner a lap dance to their favorite song.",
        "Lightly trace your nails along your partner’s back and watch them shiver.",
        "Whisper how much you want your partner right now and describe what you’ll do.",
        "Playfully bite your partner’s lip and pull away just as they try to kiss you.",
        "Run your hands along your partner’s body but avoid their most sensitive areas.",
        "Kiss your partner’s neck and leave a trail of small marks (with consent).",
        "Playfully suggest a role-playing scenario and act it out together.",
        "Whisper how irresistible your partner is and how much you want them.",
        "Run your hands along your partner’s inner thigh and stop just before reaching their most sensitive area.",
        "Kiss your partner’s collarbone and work your way down slowly.",
        "Playfully suggest trying a new position you’ve never done before.",
        "Whisper how much your partner turns you on and describe what you’re imagining.",
        "Run your fingers through your partner’s hair and pull gently while kissing them.",
        "Kiss your partner’s stomach and work your way lower, teasing them along the way.",
        "Playfully suggest taking a shower together and make it steamy.",
        "Whisper how much you love your partner’s body and describe your favorite parts.",
        "Run your hands along your partner’s legs and stop just before reaching their inner thigh.",
        "Kiss your partner’s back and leave a trail of small marks (with consent).",
        "Playfully suggest watching something naughty together and act it out.",
        "Whisper how much you want to feel your partner’s skin against yours.",
        "Run your hands along your partner’s chest and tease them by stopping just short.",
        "Kiss your partner’s ear and whisper something naughty you’ve never said before.",
        "Playfully suggest trying a new toy or accessory together.",
        "Whisper how much you love your partner’s scent and how it drives you wild.",
        "Run your hands along your partner’s sides and stop just before reaching their waistband.",
        "Kiss your partner’s lips and leave them wanting more by pulling away.",
        "Playfully suggest a game of strip poker or truth or dare.",
        "Whisper how much you love your partner’s touch and how it makes you feel.",
        "Run your hands along your partner’s arms and stop just before reaching their hands.",
        "Kiss your partner’s neck and whisper how much you want them right now.",
        "Playfully suggest trying something new in bed and describe it in detail.",
        "Whisper how much you love your partner’s voice and how it turns you on.",
        "Run your hands along your partner’s legs and stop just before reaching their knees.",
        "Kiss your partner’s cheek and whisper something seductive you’ve never said before.",
        "Playfully suggest taking things to the next level and see how your partner reacts.",
    ]
};

// Function to generate a random dare
function generateDare() {
    const category = document.getElementById("category").value;
    const dareList = dares[category];

    if (dareList.length === 0) {
        document.getElementById("dare-text").textContent = "No dares added in this category yet!";
        return;
    }
    
    // Pick a random dare
    const randomDare = dareList[Math.floor(Math.random() * dareList.length)];
    
    // Update the text on the page
    document.getElementById("dare-text").textContent = randomDare;
    
    // Add animation
    document.getElementById("dare-text").classList.add("fade");
    
    // Remove animation effect after 1 second
    setTimeout(() => {
        document.getElementById("dare-text").classList.remove("fade");
    }, 1000);
}